#!/usr/bin/env zsh
set -euo pipefail

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
bridge_file="$repo_root/VisionRep/Services/LiveRepetitionCounterBridge.swift"
model_file="$repo_root/VisionRep/Models/WorkoutSessionModel.swift"

test -f "$bridge_file"
rg -q 'final class LiveRepetitionCounterBridge' "$bridge_file"
rg -q 'DispatchQueue\(label: "com\.visionrep\.repetition\.counter"' "$bridge_file"
rg -q 'private let targetFramesPerSecond: Double = 12' "$bridge_file"
rg -q 'private var lastReportedRepetitions = 0' "$bridge_file"
rg -q 'private var lastAcceptedFrameTimestamp: TimeInterval = -\.infinity' "$bridge_file"
rg -q 'private var pendingFrame: PendingFrame\?' "$bridge_file"
rg -U -q 'func load\(templates: \[MovementTemplate\]\) \{\n\s*discardPendingFrames\(\)\n\s*resetThrottle\(\)\n\s*resetActualFrameRateWindow\(\)\n\s*resetLastReportedRepetitions\(\)\n\s*queue\.async' "$bridge_file"
rg -U -q 'func resetCount\(\) \{\n\s*discardPendingFrames\(\)\n\s*resetThrottle\(\)\n\s*resetActualFrameRateWindow\(\)\n\s*resetLastReportedRepetitions\(\)\n\s*queue\.async' "$bridge_file"
rg -q 'resetThrottle\(\)' "$bridge_file"
rg -q 'guard shouldAcceptFrame\(timestamp: frame\.timestamp\) else' "$bridge_file"
rg -q 'pendingFrame = item' "$bridge_file"
rg -q 'private func shouldAcceptFrame\(timestamp: TimeInterval\) -> Bool' "$bridge_file"
rg -q 'private var minimumFrameInterval: TimeInterval' "$bridge_file"
rg -q 'let countedNewRepetition = recordReportedRepetitions\(update\.repetitions\)' "$bridge_file"
rg -q 'if countedNewRepetition \{' "$bridge_file"
rg -q 'discardPendingFrames\(olderThan: item\.frame\.timestamp\)' "$bridge_file"
rg -q 'private func resetLastReportedRepetitions\(\)' "$bridge_file"
rg -q 'private func recordReportedRepetitions\(_ repetitions: Int\) -> Bool' "$bridge_file"
rg -q 'private func discardPendingFrames\(olderThan deadline: TimeInterval = \.infinity\)' "$bridge_file"
! rg -q 'pendingFrames|removeFirst|maxPendingFrameCount' "$bridge_file"
rg -q 'func submit\(_ frame: PoseFrame, quality: PoseQuality\)' "$bridge_file"
rg -q 'counter\.update\(with: item\.frame\)' "$bridge_file"
rg -q 'DispatchQueue\.main\.async' "$bridge_file"

rg -q 'liveRepetitionCounter\.submit\(frame, quality: quality\)' "$model_file"
rg -q 'handleLiveCountUpdate' "$model_file"
rg -q 'guard mode == \.counting, isLiveCountingActive else' "$model_file"
rg -q 'liveRepetitionCounter\.load\(templates: templates\)' "$model_file"
rg -q 'liveRepetitionCounter\.resetCount\(\)' "$model_file"
rg -q 'liveRepetitionCounter\.clearOnlineTemplates\(\)' "$model_file"
! rg -q 'let update = repetitionCounter\.update\(with: frame\)' "$model_file"

echo "live count background performance bridge verified"
