#!/usr/bin/env zsh
set -euo pipefail

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
camera_file="$repo_root/VisionRep/Services/CameraFrameSource.swift"
processor_file="$repo_root/VisionRep/Services/PoseFrameProcessor.swift"
model_file="$repo_root/VisionRep/Models/WorkoutSessionModel.swift"

rg -q 'enum CameraCaptureProfile' "$camera_file"
rg -q 'case ready' "$camera_file"
rg -q 'case active' "$camera_file"
rg -q 'case adaptive\(Double\)' "$camera_file"
rg -q 'targetFramesPerSecond: Double \{' "$camera_file"
rg -U -q 'case \.ready:\n\s*12' "$camera_file"
rg -U -q 'case \.active:\n\s*24' "$camera_file"
rg -q 'func setCaptureProfile\(_ profile: CameraCaptureProfile\)' "$camera_file"
rg -q 'captureProfile\.targetFramesPerSecond' "$camera_file"
rg -q 'onActualFramesPerSecondChange' "$camera_file"
rg -q 'recordActualCameraFrameRate\(sampleBuffer\)' "$camera_file"
rg -q 'resetActualFrameRateWindow\(\)' "$camera_file"

rg -q 'func setTargetFramesPerSecond\(_ targetFramesPerSecond: Double\)' "$processor_file"
rg -q '\[24, 20, 18, 15, 12, 10, 8\]' "$processor_file"
rg -q 'onTargetFramesPerSecondChange' "$processor_file"

rg -q 'private enum PoseRuntimeProfile' "$model_file"
rg -q 'var debugCameraFramesPerSecond = 0\.0' "$model_file"
rg -q 'var debugPoseFramesPerSecond = 0\.0' "$model_file"
rg -q 'cameraFramesPerSecond: Double \{' "$model_file"
rg -q 'poseFramesPerSecond: Double \{' "$model_file"
rg -U -q 'case \.ready:\n\s*8' "$model_file"
rg -U -q 'case \.active:\n\s*24' "$model_file"
rg -q 'applyRuntimeProfile\(\.ready\)' "$model_file"
rg -q 'applyRuntimeProfile\(\.active\)' "$model_file"
rg -q 'effectivePoseFramesPerSecond\(for: profile\)' "$model_file"
rg -q 'effectiveCameraFramesPerSecond' "$model_file"
rg -q 'camera\.setCaptureProfile\(\.adaptive\(cameraFramesPerSecond\)\)' "$model_file"
rg -q 'frameBridge\.setTargetFramesPerSecond\(poseFramesPerSecond\)' "$model_file"
rg -q 'handlePoseFrameRateChange' "$model_file"
rg -q 'handleActualCameraFrameRateChange' "$model_file"
rg -q 'handleActualPoseFrameRateChange' "$model_file"
rg -q 'frameBridge\.onActualFramesPerSecondChange' "$model_file"
rg -q 'camera\.onActualFramesPerSecondChange' "$model_file"
rg -q 'camera\.setCaptureProfile\(\.adaptive\(framesPerSecond\)\)' "$model_file"
! rg -q 'debugCameraFramesPerSecond = profile\.cameraFramesPerSecond' "$model_file"
! rg -q 'debugPoseFramesPerSecond = profile\.poseFramesPerSecond' "$model_file"
rg -q 'private var targetFramesPerSecond: Double = 8' "$model_file"
rg -q 'PoseFrameProcessor\(targetFramesPerSecond: targetFramesPerSecond\)' "$model_file"
rg -q 'resetActualFrameRateWindow\(\)' "$model_file"

echo "mode-based camera and pose cadence verified"
